include/gdk.h
src/ffi_c.cpp
src/ga_session.cpp
src/ga_session.hpp
src/session.cpp
src/session.hpp
src/swift/GreenAddress/Sources/GreenAddress/GreenAddress.swift
src/swig_java/swig_gasdk.i
src/swig_python/python_extra.py_in

Clients require access to the current watch only login username to
display in settings.

Add get_watch_only_username

---

src/ga_session.cpp

The current implementation of applying defaults to the appearance
relies on the types of the server and default values being compatible.
For example for some wallets the value for "altimeout" is a string
instead of an int. This change simplifies the code and makes it agnostic
to the types of the values.

Handle server appearance values of different types

---

src/ga_auth_handlers.cpp
src/ga_auth_handlers.hpp

When sending a transaction which is replacing a previous transaction via
RBF only the fee delta should be deducted from the spending limits
otherwise the amount is effectively double counted and 2FA will be
requested where it is not required.

Correctly account for spending limits for RBF

---

src/ga_session.cpp
src/session.cpp
src/swig_python/swig_gasdk.i

Throw login_error only in the case where the server responds with 'No
password for device' to distinguish from other errors.

Fix handling of #password error from server

---

include/gdk.h

The integer subaccount parameter used to identify subaccounts is
actually the subaccount pointer value, which is usually but not
necessarily the same as the index of the subaccount from
get_subaccounts. Make this explicit in the docs.

Clarify documentation of subaccount parameter

---

subprojects/gdk_rust/gdk_electrum/src/headers/bitcoin.rs

I thought this was fixed as part of #69, but apparently this was somehow missed.

Fix SPV difficulty validation for non-retarget blocks

---

src/ga_session.cpp
src/meson.build

Reformat user agent string
1) Enforce a maximum length of 64 characters (server will reject
anything more)
2) Use the short git commit id of the gdk version for brevity
3) Append the client provided string to the gdk git commit id rather
than replacing it

Append gdk version to client user agent string

---

src/swig_python/swig_gasdk.i

SWIG Python: Fix handling of bad capsule pointers

---

.gitignore

Conventional destination for python wrapper build artifacts

Add gdk-python/ to .gitignore

---

include/gdk.h
src/ffi_c.cpp
src/ga_auth_handlers.cpp
src/ga_auth_handlers.hpp
src/ga_rust.cpp
src/ga_rust.hpp
src/ga_session.cpp
src/ga_session.hpp
src/session.cpp
src/session.hpp
src/session_common.hpp
src/swig_java/swig_gasdk.i
src/swig_python/python_extra.py_in

Calling undo will return an internal error until the corresponding backend changes are rolled out.

Expose twofactor reset undo functionality

---

.gitlab-ci.yml
subprojects/gdk_rust/gdk_common/src/be/transaction.rs
subprojects/gdk_rust/gdk_common/src/model.rs
subprojects/gdk_rust/gdk_common/src/scripts.rs
subprojects/gdk_rust/gdk_common/src/session.rs
subprojects/gdk_rust/gdk_electrum/src/account.rs
subprojects/gdk_rust/gdk_electrum/src/error.rs
subprojects/gdk_rust/gdk_electrum/src/interface.rs
subprojects/gdk_rust/gdk_electrum/src/lib.rs
subprojects/gdk_rust/gdk_electrum/src/store.rs
subprojects/gdk_rust/src/lib.rs
subprojects/gdk_rust/src/serialize.rs
subprojects/gdk_rust/tests/integration.rs
subprojects/gdk_rust/tests/test_session.rs

- Support multiple subaccounts under the root wallet seed
- Subaccounts can have different script types: P2WPKH, P2SH-P2WPKH or P2KH
- Different script types are mapped into different non-overlapping sets of subaccount numbers
- Fixes querying for wallet utxos/balance with a `num_confs` parameter
- Includes BIP44 subaccount recovery
- Includes a new `rename_account` session method (didn't exists previously and isn't used by AQUA)
- Includes some tests
TODO:

[WIP] Support for subaccounts with multiple script types

---

.gitlab-ci.yml
subprojects/gdk_rust/gdk_common/src/be/transaction.rs
subprojects/gdk_rust/gdk_common/src/model.rs
subprojects/gdk_rust/gdk_common/src/network.rs
subprojects/gdk_rust/gdk_common/src/scripts.rs
subprojects/gdk_rust/gdk_common/src/session.rs
subprojects/gdk_rust/gdk_electrum/src/account.rs
subprojects/gdk_rust/gdk_electrum/src/error.rs
subprojects/gdk_rust/gdk_electrum/src/interface.rs
subprojects/gdk_rust/gdk_electrum/src/lib.rs
subprojects/gdk_rust/gdk_electrum/src/store.rs
subprojects/gdk_rust/src/lib.rs
subprojects/gdk_rust/src/serialize.rs
subprojects/gdk_rust/tests/integration.rs
subprojects/gdk_rust/tests/test_session.rs

Based on #93
Before this, any change to any of the the network fields (like the electrum
server url) would result in a separate db.
~~Now the db dir is derived from the master xpub (encoded with
testnet version) and the network id only.~~
Now the db dir and the db encryption key are derived from an
unusual hardened path xpub (encoded with testnet version) and
the network id only.
This is a breaking change. Wallets created before this change will
loose the data in the db. However, before creating an empty db, the
wallet attempts recovery from the path used by Aqua wallet, which
currently is the only production wallet using GDK's electrum
networks. This should allow Aqua users not to loose their memos when
upgrading.
Suggested by @shesek.

rust: segregate db by network id only

---

src/ga_auth_handlers.cpp
src/ga_rust.cpp
src/ga_rust.hpp
src/ga_session.cpp
src/ga_session.hpp
src/session.cpp
src/session.hpp
src/session_common.hpp
subprojects/gdk_rust/gdk_common/src/model.rs
subprojects/gdk_rust/gdk_common/src/scripts.rs
subprojects/gdk_rust/gdk_common/src/session.rs
subprojects/gdk_rust/gdk_electrum/src/account.rs
subprojects/gdk_rust/gdk_electrum/src/interface.rs
subprojects/gdk_rust/gdk_electrum/src/lib.rs
subprojects/gdk_rust/src/lib.rs
subprojects/gdk_rust/src/serialize.rs
subprojects/gdk_rust/tests/integration.rs

Expose the new functionality through the CPP interface, with some adjustments to match the `ga_auth_handlers` flow.

rust: Followup changes for multi-account support (#93)

---

subprojects/gdk_rust/gdk_common/src/be/mod.rs
subprojects/gdk_rust/gdk_common/src/model.rs
subprojects/gdk_rust/gdk_common/src/session.rs
subprojects/gdk_rust/gdk_electrum/src/account.rs
subprojects/gdk_rust/gdk_electrum/src/interface.rs
subprojects/gdk_rust/gdk_electrum/src/lib.rs
subprojects/gdk_rust/src/lib.rs
subprojects/gdk_rust/src/serialize.rs
subprojects/gdk_rust/tests/integration.rs
subprojects/gdk_rust/tests/test_session.rs

Before this change unconfidential (unblinded) outputs were ignored
by the wallet. Now such outputs contribute to the balance and will
be spent by default.
Consistently with the ga_session.cpp implementation, callers who
only want the balance from confidential utxos only or do not want
to spend unblinded utxos, should set "confidential" or
"confidential_utxos_only" to true.

 rust: spend unconfidential utxos

---

.gitlab-ci.yml
subprojects/gdk_rust/gdk_electrum/src/account.rs
subprojects/gdk_rust/tests/integration.rs
subprojects/gdk_rust/tests/test_session.rs

Before this change, we were always using the p2shwpkh script to
derive the blinding public key from the master blinding key. As
a result the address generated had an unexpected blinding public
key, which later caused an unblinding failure and made the fund
unspendable.
Funds are not definitively lost as the blinding key was still
deterministic, but it's not trivial to recover them. Anyway, this
never went live on a production app.

rust: elements: fix p2wpkh, p2pkh address generation

---

.gitlab-ci.yml
subprojects/gdk_rust/tests/integration.rs

This also fixes flaky test failures.

rust: tests: rename so they can be run separately

---

subprojects/gdk_rust/gdk_electrum/Cargo.toml

`zeroize` upgraded its MSRV to 1.51, but ours is still 1.42.

rust: pin zeroize

---

src/ga_rust.cpp
src/ga_rust.hpp
subprojects/gdk_rust/apple-exported-symbols
subprojects/gdk_rust/exported-symbols
subprojects/gdk_rust/gdk_common/src/model.rs
subprojects/gdk_rust/gdk_common/src/session.rs
subprojects/gdk_rust/gdk_electrum/src/lib.rs
subprojects/gdk_rust/gdk_rust.h
subprojects/gdk_rust/src/lib.rs

The initial GDK rust implementation consisted in a binary that could
replace the C++ binary. In the following iterations `gdk_rust` became
a component of the library and is called by the C++ code.
However the interface exposed by rust, `gdk_rust.h`, was never
adapted accordingly. So we had unused code, an overcomplicated
interface and some memory leaks.
This MR is an initial attempt to address those issues.
In details:
- Remove unused code
- Replace some rust macros
- Replace `GDKRUST_json` with string, since the conversion was performed every time anyway
- Remove usage of `std::mem::transmute`
- Make `GDKRUST_session` a void pointer, since C++ caller does not need to access its internal
- Add `GDKRUST_destroy_

Refactor gdk_rust.h interface

---

subprojects/gdk_rust/gdk_electrum/src/account.rs
subprojects/gdk_rust/tests/integration.rs
subprojects/gdk_rust/tests/test_session.rs

With the recent `cargo test` changes,
now tests are run with higher parallelism,
which make them even more flaky.
This MR attempts to fix some of the issues that
arose in some of the past CI runs.

rust: tests: cleanup to reduce flakiness

---

subprojects/gdk_rust/gdk_common/src/model.rs
subprojects/gdk_rust/gdk_electrum/src/account.rs
subprojects/gdk_rust/tests/integration.rs
subprojects/gdk_rust/tests/test_session.rs

Unlike "default", which was already available, "manual" will use all
and only the utxos passed in.

rust: implement "manual" utxos_strategy

---

src/ga_tx.cpp

Disable multi-asset spend on all networks

---

src/swig_python/contrib/gdk_example_liquid_amp.py

This PR updates the AMP example script to latest gdk (49-cp39-cp39 wheel). 
- add `get_unspent_outputs` function and use it in `send_to_address`.
- put network name in static variable (NETWORK_NAME).
The following is a transaction made by the script on testnet: https://blockstream.info/liquidtestnet/tx/a7764964b7be8136c30a9f6ce067ae5fd986e2dd42578b4cd26437b2be4f0500

update gdk_example_liquid_amp.py with 0.49

---

src/network_parameters.cpp

Use new url for server. Old clients will continue to be able to connect
via a redirect. Set the pinned certs to empty in line with liquid
testnet, pinning checks not necessary for testnets.

wip: Use new bitcoin testnet backend server

---

src/swig_java/swig_gasdk.i

These calls were mapped incorrectly as taking a `long` argument, and then not returning the actual value.
In generated code this turns e.g.:
```
SWIGEXPORT jlong JNICALL Java_com_blockstream_libgreenaddress_GDK_validate_1mnemonic(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
jlong jresult = 0 ;
char *arg1 = (char *) 0 ;
uint32_t *arg2 = (uint32_t *) 0 ;
int result;
(void)jenv;
(void)jcls;
arg1 = 0;
if (jarg1) {
arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
if (!arg1) return 0;
}
arg2 = jarg2;
{
result = (int)GA_validate_mnemonic((char const *)arg1,arg2);
check_result(jenv, result, "GA_validate_mnemonic");
}
if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
return jresult;
}
```
into:
```
SWIGEXPORT jlong JNICALL …
```

Java: Fix swig mapping for functions returning uint32_t

---

src/swig_python/swig_gasdk.i

With these fixes I am unable to reproduce a hang-on-test-exit condition that otherwise seems to show up semi-regularly.

Python threading

---

CHANGELOG.md
docs/source/gdk-json.rst
src/assertion.cpp
src/assertion.hpp
src/boost_wrapper.hpp
src/ga_cache.cpp
src/ga_tx.cpp
src/http_client.cpp
src/logging.hpp
src/signer.cpp
src/signer.hpp
src/socks_client.cpp
src/transaction_utils.cpp

Minimal changes required for upcoming release.
- Bump the tx cache version
- Provide ephemeral public key for blinding/signing
- Add a "supports_external_blinding" capability for HWW
- Logging/assertion updates
Note that "supports_external_blinding" defaults to true but will revert to false post-release.

0.63 pre-release updates

---

src/swig_python/contrib/gdk_example_liquid_amp.py

`blind_transaction` must now be called explicitly before signing. This allows the example to pass locally for me against testnet.

python: update liquid example to blind the transaction explicitly
